name: Wookiee Unicaster Build

on:
  #push:
    #branches: [ main ]
  #pull_request:
    #branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
    - name: Set up latest Python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Nuitka
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
    - name: Compile Wookie Unicaster
      run: |
        ./nuitka_build.bat
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wookiee_unicaster_latest_windows_x64
        path: bin\*

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
    - name: Set up latest Python version
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install Nuitka
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
    - name: Compile Wookie Unicaster
      run: |
        chmod +x nuitka_build.sh
        ./nuitka_build.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wookiee_unicaster_latest_linux_x64
        path: bin/*

